### ISSUE TITLE
Clone or use as composer dependency?

### ISSUE THREAD

**Issue by heddn** [glensc/slack-unfurl#9]
All the providers say something like:

> Register provider: in src/Application.php add $this->register(new \GitlabSlackUnfurl\ServiceProvider\GitlabUnfurlServiceProvider());

Which means we need to kinda fork this project and hack at it. Is there any way to create our own composer based project, add the app.php and register things in our own code and only use this project as a dependency instead? Or do I need to clone it, edit it, commit to my own private repo and push it Heroku, AWS Lambda, etc all own my own?

**Comment by glensc** [comment]
I had an idea to have a composer plugin to register automatically. but never got that far:
- https://github.com/glensc/slack-unfurl/tree/composer-plugin

So the current idea is you modify and don't commit the changes.

You can use as a dependency, you just need to instantiate `Application` and call register on the instance:

```php

$app = new Application();

$app->register(new \Eventum\SlackUnfurl\ServiceProvider\EventumUnfurlServiceProvider());
$app->register(new \GitlabSlackUnfurl\ServiceProvider\GitlabUnfurlServiceProvider());
$app->run();
```

**Comment by glensc** [comment]
Maybe it's clearer to update readme files to patch `index.php`?
- https://github.com/glensc/slack-unfurl/blob/v0.10.0/web/index.php#L3

as just need the register calls before `$app->run()` is invoked.

**Comment by heddn** [comment]
What you provided is exactly what I needed. Here's a working example for gitlab: https://git.mtech-llc.com/open-source/gitlab-unfurl
